# Generated by Django 4.0.5 on 2022-06-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='specialization',
            name='title',
        ),
        migrations.AddField(
            model_name='specialization',
            name='spec_id',
            field=models.IntegerField(default=0, verbose_name='Id'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='spec_title',
            field=models.CharField(default='', max_length=50, verbose_name='Specialization title'),
        ),
    ]
