# Generated by Django 4.0.5 on 2022-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_specialization_specialization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dis_id', models.IntegerField()),
                ('dis_name', models.CharField(max_length=60, verbose_name='Назва хвороби')),
                ('profylaxy', models.CharField(max_length=200, verbose_name='Профілактика')),
                ('treatment', models.CharField(max_length=200, verbose_name='Лікування')),
            ],
            options={
                'verbose_name': 'Хвороба',
                'verbose_name_plural': 'Хвороби',
            },
        ),
        migrations.AlterModelOptions(
            name='specialization',
            options={'verbose_name': 'Спеціалізація', 'verbose_name_plural': 'Спеціалізації'},
        ),
        migrations.AlterField(
            model_name='specialization',
            name='spec_id',
            field=models.IntegerField(verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='spec_title',
            field=models.CharField(max_length=50, verbose_name='Назва спеціалізації'),
        ),
    ]
