# Generated by Django 4.0.5 on 2022-06-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_disease_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_id', models.IntegerField(verbose_name='Id')),
                ('fullName', models.CharField(max_length=100, verbose_name="Повне ім'я")),
                ('adress', models.CharField(max_length=200, verbose_name='Адреса проживання')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('insurancepolicy', models.CharField(max_length=60, verbose_name='Страховий поліс')),
                ('passportId', models.CharField(max_length=45, verbose_name='Номер паспорту')),
            ],
            options={
                'verbose_name': 'Пацієнт',
                'verbose_name_plural': 'Пацієнти',
            },
        ),
        migrations.AlterField(
            model_name='disease',
            name='dis_id',
            field=models.IntegerField(verbose_name='Id'),
        ),
    ]
