# Generated by Django 4.0.5 on 2022-06-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_patient_alter_disease_dis_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialization',
            name='id',
        ),
        migrations.AlterField(
            model_name='disease',
            name='dis_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pat_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='spec_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='Id'),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.IntegerField(null=True, unique=True, verbose_name='Id')),
                ('fullName', models.CharField(max_length=45, verbose_name="Повне ім'я")),
                ('position', models.CharField(max_length=45, verbose_name='Посада')),
                ('workExp', models.CharField(max_length=45, verbose_name='Досвід роботи')),
                ('adress', models.CharField(max_length=100, verbose_name='Адреса проживання')),
                ('phoneNumber', models.CharField(max_length=15, verbose_name='Номер телефону')),
                ('spec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.specialization')),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diag_id', models.IntegerField(verbose_name='Id')),
                ('dateOfApplication', models.CharField(max_length=45, verbose_name='Дата запису')),
                ('dateOfRecovery', models.CharField(max_length=45, verbose_name='Дата одужання')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disease', to_field='dis_id')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.doctor', to_field='doc_id')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.patient', to_field='pat_id')),
            ],
            options={
                'verbose_name': 'Діагноз',
                'verbose_name_plural': 'Діагнози',
            },
        ),
    ]
