# Generated by Django 4.0.5 on 2022-06-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_specialization_id_alter_disease_dis_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='diag_id',
            field=models.IntegerField(unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='dis_id',
            field=models.IntegerField(default='0', unique=True, verbose_name='Id'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='dis_name',
            field=models.CharField(max_length=60, verbose_name='Лікування'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='treatment',
            field=models.CharField(max_length=200, verbose_name='Назва хвороби'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='fullName',
            field=models.CharField(max_length=45, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phoneNumber',
            field=models.CharField(max_length=15, verbose_name="Повне ім'я"),
        ),
        migrations.AlterField(
            model_name='patient',
            name='fullName',
            field=models.CharField(max_length=100, verbose_name='Номер паспорту'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='passportId',
            field=models.CharField(max_length=45, verbose_name="Повне ім'я"),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='spec_id',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True, verbose_name='Id'),
        ),
    ]
